name: Nahlášení chyb
description: Nahlášení chyb
body:
  - type: markdown
    attributes:
      value: |
        Děkujeme za nahlášení chyby. Pro správné řešení chyby je potřeba, aby byly vyplněny všechny položky.
  - type: input
    id: url-path
    attributes:
      label: URL adresa
      description: URL adresa, na které jste narazili na chybu.
      placeholder: https://www.pirati.cz/...
    id: what-happened
    attributes:
      label: Co se stalo?
      description: Popište co se stalo.
      placeholder: |
        Například: "Nelze se přihlásit."
  - type: textarea
    id: what-should-happen
    attributes:
      label: Co by se mělo stát?
      description: Popište co by se mělo stát.
      placeholder: |
        Například: "Měl bych se přihlásit."
  - type: textarea
    id: screenshots
    attributes:
      label: Snímky obrazovky
      description: Pokud je to možné, přiložte snímky obrazovky.
      placeholder: |
        Například: "![Snímek obrazovky](https://example.com/image.png)"
