name: Nahlášení chyb
description: Nahlášení chyb
title: "Chyba: "
assignees: 
  - michalhejd
  - danbulant
body:
  - type: markdown
    attributes:
      value: |
        Děkujeme za nahlášení chyby. Pro správné řešení chyby je potřeba, aby byly vyplněny všechny položky.
  - type: textarea
    id: what-happened
    attributes:
      label: Co se stalo?
      description: Popište co se stalo.
      placeholder: |
        Například: "Nelze se přihlásit."
  - type: textarea
    id: what-should-happen
    attributes:
      label: Co by se mělo stát?
      description: Popište co by se mělo stát.
      placeholder: |
        Například: "Měl bych se přihlásit."
  - type: textarea
    id: URL
    attributes:
      label: URL
      description: URL stránky, kde se chyba vyskytla.
      placeholder: |
        Například: "https://www.example.com"
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot
      description: Screenshot chyby.
  
